### ISSUE TITLE
Nightly support

### ISSUE THREAD

**Issue by aufkrawall** [dglava/firefox-dpms#2]
Hello,
would it be possible to add support for Firefox Nightly? I suppose the sink detection needs to be adjusted for this.

Thanks!

**Comment by dglava** [comment]
Can you play a video back in Firefox Nightly, on Youtube for example, and post the output of `pactl list sink-inputs | grep application.name`?

I have installed Nightly and the name of the sink-input is "AudioIPC Server". The standard Firefox one has it set to the appropriate "Firefox", so I want to see if this isn't just an oddity on my end.

**Comment by aufkrawall** [comment]
I can confirm this:
```
Stable:
application.name = "Firefox"
module-stream-restore.id = "sink-input-by-application-name:Firefox"

Beta:
application.name = "Firefox"
module-stream-restore.id = "sink-input-by-application-name:Firefox"

Developer Edition:
application.name = "Firefox Developer Edition"
module-stream-restore.id = "sink-input-by-application-name:Firefox Developer Edition"

Nightly:
application.name = "AudioIPC Server"
module-stream-restore.id = "sink-input-by-application-name:AudioIPC Server"
```

**Comment by dglava** [comment]
Can you test it now?

**Comment by aufkrawall** [comment]
Works fine now with Nightly, finally no more screensaver woes for me in Firefox. Thanks a lot for your efforts!
